### ISSUE TITLE
Performance issue: General performance

### ISSUE THREAD

**Issue by dot-Justin** [dot-Justin/LAMAtHome#6]
**Describe the performance issue**
- Playwright generally using lots of RAM and CPU

**To Reproduce**
1. Run main.py
2. See performance issue

**Expected behavior**
- make my cpu not die pls

**Screenshots or Logs**
- If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- I'm the boss, i refuse to give this information

**Additional context**
- Look into site optimization

**Comment by dot-Justin** [comment]
@GikitSRC is currently investigating a way to connect to rabbithole's endpoint directly instead of using cpu-intensive playwright just to scrape info. This will be a hige milestone, thanks to @pnivek for bringing up the idea!

**Comment by pnivek** [comment]
Got some direction from @GikitSRC on required header/body params for hitting journal endpoint. I'm working now to add this module and assigned the issue to myself.

**Comment by pnivek** [comment]
Journal module feature branch was merged with added a new journals module. Provided we have the user auth token it adds a method for continuously grabbing user journals (with basic filtering). This uses much less CPU usage.

Tangent issue: since rabbit updated their login frontend to include captcha, we cant actually use play wright anymore to log in. This might have to be a manual step if we cant login via API (which is looking likely).
